// sdk/browser/examples/nextjs/app/page.tsx
'use client';

import { useState, useEffect } from 'react';

export default function Home() {
  const [users, setUsers] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchUsers = async () => {
    setLoading(true);
    setError(null);
    try {
      const response = await fetch('/api/users');
      if (!response.ok) {
        throw new Error(`HTTP ${response.status}`);
      }
      const data = await response.json();
      setUsers(data.users || []);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Unknown error');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchUsers();
  }, []);

  return (
    <main style={{ padding: '20px', fontFamily: 'system-ui' }}>
      <h1>ForgeConnect - Next.js Example</h1>
      <button
        onClick={fetchUsers}
        disabled={loading}
        style={{
          padding: '10px 20px',
          backgroundColor: '#007bff',
          color: 'white',
          border: 'none',
          borderRadius: '4px',
          cursor: loading ? 'not-allowed' : 'pointer',
          marginBottom: '20px',
        }}
      >
        {loading ? 'Loading...' : 'Fetch Users'}
      </button>
      {error && (
        <div style={{ color: '#dc3545', marginBottom: '20px' }}>
          Error: {error}
        </div>
      )}
      <div>
        <h2>Users</h2>
        {users.length === 0 ? (
          <p>No users found. Make a request to /api/users to create a mock!</p>
        ) : (
          <ul>
            {users.map((user) => (
              <li key={user.id}>
                {user.name} ({user.email})
              </li>
            ))}
          </ul>
        )}
      </div>
    </main>
  );
}

// sdk/browser/examples/vue/src/App.vue
<template>
  <div style="padding: 20px; font-family: system-ui">
    <h1>ForgeConnect - Vue.js Example</h1>
    <div :style="{
      padding: '10px',
      marginBottom: '20px',
      backgroundColor: connected ? '#d4edda' : '#f8d7da',
      color: connected ? '#155724' : '#721c24',
      borderRadius: '4px'
    }">
      {{ connected ? '✓ Connected to MockForge' : '✗ Not connected to MockForge' }}
    </div>
    <button @click="fetchUsers" :disabled="loading">
      {{ loading ? 'Loading...' : 'Fetch Users' }}
    </button>
    <div v-if="error" style="color: #dc3545; margin-top: 10px">
      Error: {{ error }}
    </div>
    <div v-if="users.length > 0" style="margin-top: 20px">
      <h2>Users</h2>
      <ul>
        <li v-for="user in users" :key="user.id">
          {{ user.name }} ({{ user.email }})
        </li>
      </ul>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { useForgeConnect } from '@mockforge/forgeconnect/adapters/vue';

const { connected } = useForgeConnect({
  mockMode: 'auto',
  autoMockStatusCodes: [404, 500],
  autoMockNetworkErrors: true,
});

const users = ref<any[]>([]);
const loading = ref(false);
const error = ref<string | null>(null);

const fetchUsers = async () => {
  loading.value = true;
  error.value = null;
  try {
    const response = await fetch('/api/users');
    if (!response.ok) {
      throw new Error(`HTTP ${response.status}`);
    }
    const data = await response.json();
    users.value = data.users || [];
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Unknown error';
  } finally {
    loading.value = false;
  }
};
</script>
